import { NextResponse } from "next/server";
import { spawn } from "child_process";
import path from "path";
import fs from "fs";

const AUTOCLAW_DIR = path.resolve(process.cwd(), "autoclaw");
const ACCOUNTS_FILE = path.join(AUTOCLAW_DIR, "accounts.txt");
const TOKENS_FILE = path.join(AUTOCLAW_DIR, "tokens.json");

let batchProc = null;
let batchLogs = [];
let batchStatus = "idle"; // idle | running | done | error
let batchResults = { total: 0, success: 0, failed: 0 };

function findPython() {
  const candidates = ["python3", "python", process.platform === "win32" ? "py" : null].filter(Boolean);
  for (const cmd of candidates) {
    try {
      require("child_process").execSync(`${cmd} --version`, { stdio: "ignore" });
      return cmd;
    } catch {}
  }
  return null;
}

export async function POST(req) {
  const body = await req.json();
  const { accounts } = body; // array of {email, password}

  if (!accounts || !Array.isArray(accounts) || accounts.length === 0) {
    return NextResponse.json({ error: "No accounts provided" }, { status: 400 });
  }

  const headless = body.headless !== false;
  const python = findPython();
  if (!python) {
    return NextResponse.json({ error: "Python not found" }, { status: 500 });
  }

  // Write accounts to file
  const lines = accounts.map((a) => `${a.email}:${a.password}`);
  const content = "# AutoClaw batch import — generated by 9Router\n" + lines.join("\n");
  fs.writeFileSync(ACCOUNTS_FILE, content);

  // Reset state
  batchLogs = [];
  batchResults = { total: accounts.length, success: 0, failed: 0 };
  batchStatus = "running";

  // Run autoclaw_autologin.py --batch
  const script = path.join(AUTOCLAW_DIR, "autoclaw_autologin.py");
  const args = ["--batch", "accounts.txt"];
  if (headless) args.unshift("--headless");
  if (!fs.existsSync(script)) {
    return NextResponse.json({ error: "autoclaw_autologin.py not found. Copy it to autoclaw/ directory." }, { status: 500 });
  }

  const env = { ...process.env, PYTHONUNBUFFERED: "1" };

  if (batchProc) {
    batchProc.kill("SIGTERM");
  }

  batchProc = spawn(python, [script, ...args], {
    cwd: AUTOCLAW_DIR,
    env,
    stdio: ["pipe", "pipe", "pipe"],
  });

  batchProc.stdout.on("data", (data) => {
    const text = data.toString();
    batchLogs.push(text);
    if (text.includes("✅")) batchResults.success++;
    if (text.includes("❌")) batchResults.failed++;
  });

  batchProc.stderr.on("data", (data) => {
    batchLogs.push(data.toString());
  });

  batchProc.on("close", (code) => {
    batchStatus = code === 0 ? "done" : "error";
    batchProc = null;
  });

  return NextResponse.json({
    status: "started",
    accounts: accounts.length,
    headless,
    message: `Batch import started: ${accounts.length} accounts`,
  });
}

export async function GET() {
  return NextResponse.json({
    status: batchStatus,
    logs: batchLogs.slice(-200),
    results: batchResults,
    running: !!batchProc,
  });
}

export async function DELETE() {
  if (batchProc) {
    batchProc.kill("SIGTERM");
    setTimeout(() => { if (batchProc) batchProc.kill("SIGKILL"); }, 5000);
    batchProc = null;
  }
  batchStatus = "idle";
  return NextResponse.json({ status: "cancelled" });
}
